apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: mongo
  name: mongo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: mongo
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: mongo
    spec:
      containers:
      - image: mongo:latest
        imagePullPolicy: IfNotPresent
        name: mongo
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
