apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: neo-privnet
  name: neo-privnet
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: neo-privnet
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: neo-privnet
    spec:
      containers:
      - image: metachris/neo-privnet-with-gas
        imagePullPolicy: IfNotPresent
        name: neo-privnet
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
