apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: neon-wallet-db
  name: neon-wallet-db
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: neon-wallet-db
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: neon-wallet-db
    spec:
      containers:
      - env:
        - name: MONGOURL
          value: mongo:27017
        - name: MONGOPASS
          value: neo
        - name: MONGOUSER
          value: gas
        - name: MONGOAPP
          value: test
        - name: REDISTOGO_URL
          value: redis://redis:6379
        - name: PYTHONUNBUFFERED
          value: "0"
        - name: NET
          value: private
        - name: PRIVNET_SEEDS
          value: http://[NEOEXTERNALIP]:30333,http://[NEOEXTERNALIP]:30334,http://[NEOEXTERNALIP]:30335,http://[NEOEXTERNALIP]:30336
        image: slipoh/neon-wallet-db:latest
        imagePullPolicy: IfNotPresent
        name: neon-wallet-db
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
