apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: mongo
  name: mongo
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: mongo
    port: 27017
    targetPort: 27017
  selector:
    run: mongo
  sessionAffinity: None
  type: NodePort

