apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: neon-wallet-db
  name: neon-wallet-db
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: neon-wallet-db
    port: 5000
    targetPort: 5000
  selector:
    run: neon-wallet-db
  sessionAffinity: None
  type: LoadBalancer

