apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: postgres
  name: postgres
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
  selector:
    run: postgres
  sessionAffinity: None
  type: NodePort

