apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: redis
  name: redis
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  selector:
    run: redis
  sessionAffinity: None
  type: NodePort

